apiVersion: v1
kind: Service
metadata:
  name: default-backend-svc
  namespace: ingress
spec:
  type: ClusterIP
  selector:
    app: default-backend
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
